#pragma once
#include "../../support.hpp"
#include <cmath>
namespace algs {
struct CircuitOpenError : std::runtime_error { CircuitOpenError(): std::runtime_error("Circuit is open") {} };
struct CircuitBreakerOptions { int failureThreshold = 3; double resetTimeoutMs = 10000; std::function<double()> now = [] { return double(nowMs()); }; };
template<class A, class R> class CircuitBreaker { std::function<std::future<R>(A)> action; CircuitBreakerOptions options; int failures = 0; double openedAt = 0; std::string current = "closed"; bool probing = false; std::mutex mutex; std::string readState() { if (current == "open" && options.now() - openedAt >= options.resetTimeoutMs) current = "half-open"; return current; } public: CircuitBreaker(std::function<std::future<R>(A)> action, CircuitBreakerOptions options = {}): action(std::move(action)), options(std::move(options)) {} std::string state() { std::lock_guard lock(mutex); return readState(); } std::future<R> call(A args) { { std::lock_guard lock(mutex); auto status = readState(); if (status == "open" || (status == "half-open" && probing)) return failedFuture<R>(std::make_exception_ptr(CircuitOpenError())); if (status == "half-open") probing = true; } return std::async(std::launch::async, [this, args = std::move(args)] { try { R value = action(args).get(); std::lock_guard lock(mutex); failures = 0; current = "closed"; probing = false; return value; } catch (...) { std::lock_guard lock(mutex); ++failures; if (current == "half-open" || failures >= options.failureThreshold) { current = "open"; openedAt = options.now(); } probing = false; throw; } }); } };
struct RetryOptions { int attempts = 3; double delayMs = 0, factor = 2; };
template<class R> std::future<R> retry(std::function<std::future<R>()> action, RetryOptions options = {}) { return std::async(std::launch::async, [action = std::move(action), options] { if (options.attempts < 1) throw std::invalid_argument("Attempts must be positive"); for (int attempt = 0; ; ++attempt) { try { return action().get(); } catch (...) { if (attempt + 1 == options.attempts) throw; if (options.delayMs > 0) std::this_thread::sleep_for(std::chrono::duration<double, std::milli>(options.delayMs * std::pow(options.factor, attempt))); } } }); }
}
