#pragma once
#include "../../shared/json.hpp"
namespace algs {
struct CounterAction { std::string type; double amount = 0; };
inline double counterReducer(double state, const CounterAction& action) { if (action.type == "increment") return state + 1; if (action.type == "decrement") return state - 1; if (action.type == "add") return state + action.amount; throw std::invalid_argument("Unknown counter action"); }
template<class S, class A> class Store { S state; std::function<S(const S&, const A&)> reducer; struct Listeners { std::vector<std::shared_ptr<std::function<void()>>> items; }; std::shared_ptr<Listeners> listeners = std::make_shared<Listeners>(); bool dispatching = false; public: Store(std::function<S(const S&, const A&)> reducer, S initial): state(std::move(initial)), reducer(std::move(reducer)) {} const S& getState() const { return state; } A dispatch(A action) { if (dispatching) throw std::logic_error("Reducers may not dispatch actions"); dispatching = true; try { state = reducer(state, action); dispatching = false; } catch (...) { dispatching = false; throw; } auto snapshot = listeners->items; for (auto& listener : snapshot) (*listener)(); return action; } std::function<void()> subscribe(std::shared_ptr<std::function<void()>> listener) { if (std::find(listeners->items.begin(), listeners->items.end(), listener) == listeners->items.end()) listeners->items.push_back(listener); std::weak_ptr<Listeners> weak = listeners; return [weak, listener] { if (auto state = weak.lock()) std::erase(state->items, listener); }; } };
template<class S, class A> Store<S, A> createStore(std::function<S(const S&, const A&)> reducer, S initial) { return {std::move(reducer), std::move(initial)}; }
template<class A> auto combineReducers(std::map<std::string, std::function<Json(const Json&, const A&)>> reducers) { return [reducers = std::move(reducers)](const Json::Object& state, const A& action) { auto next = state; bool changed = false; for (auto& [key, reducer] : reducers) { auto value = reducer(state.at(key), action); changed = changed || !(value == state.at(key)); next[key] = std::move(value); } return changed ? next : state; }; }
}
