#pragma once
#include "../../support.hpp"
namespace algs {
struct TextDocument { std::string content; };
struct Command { virtual ~Command() = default; virtual void execute() = 0; virtual void undo() = 0; };
inline std::size_t slicePosition(long long position, std::size_t length) { return position < 0 ? std::size_t(std::max(0LL, static_cast<long long>(length) + position)) : std::min(std::size_t(position), length); }
class InsertCommand : public Command { TextDocument& document; long long position; std::string inserted; public: InsertCommand(TextDocument& document, long long position, std::string inserted): document(document), position(position), inserted(std::move(inserted)) {} void execute() override { document.content.insert(slicePosition(position, document.content.size()), inserted); } void undo() override { auto from = slicePosition(position, document.content.size()), to = slicePosition(position + static_cast<long long>(inserted.size()), document.content.size()); document.content = document.content.substr(0, from) + document.content.substr(to); } };
class DeleteCommand : public Command { TextDocument& document; long long position, length; std::string removed; public: DeleteCommand(TextDocument& document, long long position, long long length): document(document), position(position), length(length) {} void execute() override { auto from = slicePosition(position, document.content.size()), to = slicePosition(position + length, document.content.size()); removed = to > from ? document.content.substr(from, to - from) : ""; document.content = document.content.substr(0, from) + document.content.substr(to); } void undo() override { document.content.insert(slicePosition(position, document.content.size()), removed); } };
class MacroCommand : public Command { std::vector<std::shared_ptr<Command>> commands; public: explicit MacroCommand(std::vector<std::shared_ptr<Command>> commands): commands(std::move(commands)) {} void execute() override { for (auto& command : commands) command->execute(); } void undo() override { for (auto it = commands.rbegin(); it != commands.rend(); ++it) (*it)->undo(); } };
class CommandHistory { std::vector<std::shared_ptr<Command>> done, undone; public: void run(std::shared_ptr<Command> command) { command->execute(); done.push_back(std::move(command)); undone.clear(); } bool undo() { if (done.empty()) return false; auto command = done.back(); done.pop_back(); command->undo(); undone.push_back(command); return true; } bool redo() { if (undone.empty()) return false; auto command = undone.back(); undone.pop_back(); command->execute(); done.push_back(command); return true; } };
}
