#pragma once
#include "../../support.hpp"
#include <regex>
namespace algs {
using Context = std::map<std::string, double>;
struct Expression { virtual ~Expression() = default; virtual double interpret(const Context& context = {}) const = 0; virtual std::string toString() const = 0; };
class NumberExpression : public Expression { double value; public: explicit NumberExpression(double value): value(value) {} double interpret(const Context& = {}) const override { return value; } std::string toString() const override { return text(value); } };
class VariableExpression : public Expression { std::string name; public: explicit VariableExpression(std::string name): name(std::move(name)) {} double interpret(const Context& context = {}) const override { return context.at(name); } std::string toString() const override { return name; } };
class BinaryExpression : public Expression { char op; std::shared_ptr<Expression> left, right; public: BinaryExpression(char op, std::shared_ptr<Expression> left, std::shared_ptr<Expression> right): op(op), left(std::move(left)), right(std::move(right)) {} double interpret(const Context& context = {}) const override { auto a = left->interpret(context), b = right->interpret(context); switch (op) { case '+': return a + b; case '-': return a - b; case '*': return a * b; case '/': return a / b; default: throw std::invalid_argument("Unknown operator"); } } std::string toString() const override { return "(" + left->toString() + ' ' + op + ' ' + right->toString() + ')'; } };
inline std::shared_ptr<Expression> parseExpression(const std::string& source) { std::regex pattern("[0-9]+(?:\\.[0-9]+)?|[A-Za-z_][A-Za-z_0-9]*|[-+*/()]"); std::vector<std::string> tokens; for (auto it = std::sregex_iterator(source.begin(), source.end(), pattern); it != std::sregex_iterator(); ++it) tokens.push_back(it->str()); std::size_t position = 0; auto peek = [&] { return position < tokens.size() ? tokens[position] : ""; }; auto consume = [&] { if (position == tokens.size()) throw std::invalid_argument("Unexpected end of expression"); return tokens[position++]; }; std::function<std::shared_ptr<Expression>()> sum, product, primary; primary = [&]() -> std::shared_ptr<Expression> { auto token = consume(); if (token == "(") { auto inner = sum(); if (consume() != ")") throw std::invalid_argument("Expected )"); return inner; } if (std::isdigit(static_cast<unsigned char>(token[0]))) return std::make_shared<NumberExpression>(std::stod(token)); if (std::isalpha(static_cast<unsigned char>(token[0])) || token[0] == '_') return std::make_shared<VariableExpression>(token); throw std::invalid_argument("Unexpected token"); }; product = [&] { auto result = primary(); while (peek() == "*" || peek() == "/") { auto op = consume(); result = std::make_shared<BinaryExpression>(op[0], result, primary()); } return result; }; sum = [&] { auto result = product(); while (peek() == "+" || peek() == "-") { auto op = consume(); result = std::make_shared<BinaryExpression>(op[0], result, product()); } return result; }; auto result = sum(); if (position != tokens.size()) throw std::invalid_argument("Unexpected token"); return result; }
}
