#pragma once
#include "../../support.hpp"
#include <ranges>
namespace algs {
class NumberRange { double start, finish, step; public: NumberRange(double start, double end, double step = 1): start(start), finish(end), step(step) { if (step == 0) throw std::invalid_argument("Step must not be zero"); } struct ClassicIterator { double current, end, step; bool hasNext() const { return step > 0 ? current < end : current > end; } double next() { double value = current; current += step; return value; } }; ClassicIterator createIterator() const { return {start, finish, step}; } struct Iterator { double current, finish, step; double operator*() const { return current; } Iterator& operator++() { current += step; return *this; } bool operator!=(std::default_sentinel_t) const { return step > 0 ? current < finish : current > finish; } }; Iterator begin() const { return {start, finish, step}; } std::default_sentinel_t end() const { return {}; } };
template<class T> struct TreeItem { T value; std::vector<TreeItem> children; };
template<class T> class TreeTraversal { const std::vector<TreeItem<T>>& roots; bool breadth; public: TreeTraversal(const std::vector<TreeItem<T>>& roots, bool breadth): roots(roots), breadth(breadth) {} class Iterator { std::deque<const TreeItem<T>*> pending; bool breadth; public: Iterator(const std::vector<TreeItem<T>>& roots, bool breadth): breadth(breadth) { for (auto& root : roots) pending.push_back(&root); } const T& operator*() const { return pending.front()->value; } Iterator& operator++() { auto node = pending.front(); pending.pop_front(); if (breadth) for (auto& child : node->children) pending.push_back(&child); else for (auto it = node->children.rbegin(); it != node->children.rend(); ++it) pending.push_front(&*it); return *this; } bool operator!=(std::default_sentinel_t) const { return !pending.empty(); } }; Iterator begin() const { return {roots, breadth}; } std::default_sentinel_t end() const { return {}; } };
template<class T> TreeTraversal<T> depthFirst(const std::vector<TreeItem<T>>& roots) { return {roots, false}; }
template<class T> TreeTraversal<T> breadthFirst(const std::vector<TreeItem<T>>& roots) { return {roots, true}; }
template<class Range> class TakeRange { Range source; long long count; public: TakeRange(Range source, long long count): source(std::move(source)), count(std::max(0LL, count)) {} struct Iterator { decltype(std::declval<Range&>().begin()) current; decltype(std::declval<Range&>().end()) end; long long remaining; decltype(auto) operator*() const { return *current; } Iterator& operator++() { --remaining; if (remaining) ++current; return *this; } bool operator!=(std::default_sentinel_t) const { return remaining > 0 && current != end; } }; Iterator begin() { return {source.begin(), source.end(), count}; } std::default_sentinel_t end() const { return {}; } };
template<class Range> TakeRange<Range> take(Range source, long long count) { return {std::move(source), count}; }
}
