#pragma once
#include "../../shared/json.hpp"
#include <cmath>
namespace algs {
struct SalesRecord { std::string product; double amount; }; struct SalesReport { double total; std::optional<std::string> topProduct; std::size_t records; };
class SalesDataMiner { protected: virtual std::vector<SalesRecord> parse(const std::string& raw) const = 0; virtual bool isValid(const SalesRecord& record) const { return !record.product.empty() && std::isfinite(record.amount) && record.amount >= 0; } virtual SalesReport report(const std::vector<SalesRecord>& records) const { std::map<std::string, double> totals; std::vector<std::string> order; double total = 0; for (auto& record : records) { if (!totals.count(record.product)) order.push_back(record.product); totals[record.product] += record.amount; total += record.amount; } std::optional<std::string> top; for (auto& product : order) if (!top || totals[product] > totals[*top]) top = product; return {total, top, records.size()}; } public: virtual ~SalesDataMiner() = default; SalesReport mine(const std::string& raw) const { auto records = parse(raw); std::erase_if(records, [&](auto& record) { return !isValid(record); }); return report(records); } };
class CsvSalesMiner : public SalesDataMiner { static std::string trim(std::string value) { auto first = value.find_first_not_of(" \t\r\n"), last = value.find_last_not_of(" \t\r\n"); return first == std::string::npos ? "" : value.substr(first, last - first + 1); } protected: std::vector<SalesRecord> parse(const std::string& raw) const override { std::istringstream in(trim(raw)); std::string line; std::getline(in, line); std::vector<SalesRecord> records; while (std::getline(in, line)) { auto comma = line.find(','); auto product = trim(line.substr(0, comma)), amount = comma == std::string::npos ? "" : trim(line.substr(comma + 1)); auto next = amount.find(','); amount = amount.substr(0, next); double value = 0; if (!amount.empty()) { try { std::size_t consumed; value = std::stod(amount, &consumed); if (consumed != amount.size()) value = std::numeric_limits<double>::quiet_NaN(); } catch (...) { value = std::numeric_limits<double>::quiet_NaN(); } } records.push_back({product, value}); } return records; } };
class JsonSalesMiner : public SalesDataMiner { protected: std::vector<SalesRecord> parse(const std::string& raw) const override { std::vector<SalesRecord> records; auto parsed = Json::parse(raw); for (auto& item : parsed.array()) records.push_back({item.at("product").string(), item.at("amount").number()}); return records; } };
}
