<?php
declare(strict_types=1);

namespace Ports\Algorithms\Geometry;

use function Ports\Shared\field;
use function Ports\Algorithms\Sorting\mergeSort;
function cross(mixed $o,mixed $a,mixed $b): int|float { return (field($a,'x')-field($o,'x'))*(field($b,'y')-field($o,'y'))-(field($a,'y')-field($o,'y'))*(field($b,'x')-field($o,'x')); }
function distance(mixed $a,mixed $b): float { return hypot(field($a,'x')-field($b,'x'),field($a,'y')-field($b,'y')); }
function convexHull(array $points): array { $sorted = mergeSort($points,fn($a,$b) => (field($a,'x') <=> field($b,'x')) ?: (field($a,'y') <=> field($b,'y'))); if (count($sorted) < 3) return $sorted; $build = function(array $sequence): array { $hull = []; foreach ($sequence as $point) { while (count($hull) >= 2 && cross($hull[count($hull)-2],$hull[count($hull)-1],$point) <= 0) array_pop($hull); $hull[] = $point; } array_pop($hull); return $hull; }; return [...$build($sorted),...$build(array_reverse($sorted))]; }
function polygonArea(array $polygon): float { $area = 0; $n = count($polygon); foreach ($polygon as $i => $a) { $b = $polygon[($i+1)%$n]; $area += field($a,'x')*field($b,'y')-field($b,'x')*field($a,'y'); } return abs($area)/2; }
function pointInPolygon(mixed $point,array $polygon): bool { $inside = false; for ($i = 0,$j = count($polygon)-1; $i < count($polygon); $j = $i++) { $a = $polygon[$i]; $b = $polygon[$j]; $ay = field($a,'y'); $by = field($b,'y'); $py = field($point,'y'); if (($ay > $py) !== ($by > $py) && field($point,'x') < (field($b,'x')-field($a,'x'))*($py-$ay)/($by-$ay)+field($a,'x')) $inside = !$inside; } return $inside; }
function onSegment(mixed $p,mixed $q,mixed $r): bool { return min(field($p,'x'),field($r,'x')) <= field($q,'x') && field($q,'x') <= max(field($p,'x'),field($r,'x')) && min(field($p,'y'),field($r,'y')) <= field($q,'y') && field($q,'y') <= max(field($p,'y'),field($r,'y')); }
function segmentsIntersect(mixed $p1,mixed $p2,mixed $q1,mixed $q2): bool { $d1 = cross($p1,$p2,$q1)<=>0; $d2 = cross($p1,$p2,$q2)<=>0; $d3 = cross($q1,$q2,$p1)<=>0; $d4 = cross($q1,$q2,$p2)<=>0; return ($d1 !== $d2 && $d3 !== $d4) || ($d1 === 0 && onSegment($p1,$q1,$p2)) || ($d2 === 0 && onSegment($p1,$q2,$p2)) || ($d3 === 0 && onSegment($q1,$p1,$q2)) || ($d4 === 0 && onSegment($q1,$p2,$q2)); }
function closestPair(array $points): ?array { if (count($points) < 2) return null; $byX = mergeSort($points,fn($a,$b) => field($a,'x') <=> field($b,'x')); $best = ['a'=>$byX[0],'b'=>$byX[1],'distance'=>distance($byX[0],$byX[1])]; $solve = function(int $left,int $right) use (&$solve,&$best,$byX): array { if ($right-$left <= 3) { for ($i = $left; $i < $right; $i++) for ($j = $i+1; $j < $right; $j++) { $d = distance($byX[$i],$byX[$j]); if ($d < $best['distance']) $best = ['a'=>$byX[$i],'b'=>$byX[$j],'distance'=>$d]; } return mergeSort(array_slice($byX,$left,$right-$left),fn($a,$b) => field($a,'y') <=> field($b,'y')); } $mid = ($left+$right)>>1; $midX = field($byX[$mid],'x'); $a = $solve($left,$mid); $b = $solve($mid,$right); $merged = []; for ($i = 0,$j = 0; $i < count($a) || $j < count($b);) { if ($j >= count($b) || ($i < count($a) && field($a[$i],'y') <= field($b[$j],'y'))) $merged[] = $a[$i++]; else $merged[] = $b[$j++]; } $strip = array_values(array_filter($merged,fn($p) => abs(field($p,'x')-$midX) < $best['distance'])); for ($i = 0; $i < count($strip); $i++) for ($j = $i+1; $j < count($strip) && field($strip[$j],'y')-field($strip[$i],'y') < $best['distance']; $j++) { $d = distance($strip[$i],$strip[$j]); if ($d < $best['distance']) $best = ['a'=>$strip[$i],'b'=>$strip[$j],'distance'=>$d]; } return $merged; }; $solve(0,count($byX)); return $best; }
