#pragma once
#include "../../support.hpp"
namespace algs {
using HuffmanCodes = std::map<std::string, std::string>;
inline std::vector<std::string> utf8Symbols(const std::string& text) { std::vector<std::string> result; for (std::size_t i = 0; i < text.size();) { unsigned char c = text[i]; std::size_t length = c < 128 ? 1 : (c & 224) == 192 ? 2 : (c & 240) == 224 ? 3 : 4; if (i + length > text.size()) throw std::invalid_argument("Invalid UTF-8"); result.push_back(text.substr(i, length)); i += length; } return result; }
inline HuffmanCodes huffmanCodes(const std::string& text) { struct Node { int weight, order; std::string symbol; std::shared_ptr<Node> left, right; }; std::vector<std::pair<std::string, int>> counts; std::map<std::string, std::size_t> index; for (const auto& symbol : utf8Symbols(text)) { auto [it, added] = index.emplace(symbol, counts.size()); if (added) counts.push_back({symbol, 0}); ++counts[it->second].second; } HuffmanCodes codes; if (counts.empty()) return codes; if (counts.size() == 1) { codes[counts[0].first] = "0"; return codes; } using Link = std::shared_ptr<Node>; auto compare = [](const Link& a, const Link& b) { return a->weight == b->weight ? a->order > b->order : a->weight > b->weight; }; std::priority_queue<Link, std::vector<Link>, decltype(compare)> heap(compare); int order = 0; for (const auto& [symbol, weight] : counts) heap.push(std::make_shared<Node>(Node{weight, order++, symbol, nullptr, nullptr})); while (heap.size() > 1) { auto left = heap.top(); heap.pop(); auto right = heap.top(); heap.pop(); heap.push(std::make_shared<Node>(Node{left->weight + right->weight, order++, "", left, right})); } std::function<void(Link, std::string)> assign = [&](Link node, std::string code) { if (!node->left) { codes[node->symbol] = code; return; } assign(node->left, code + "0"); assign(node->right, code + "1"); }; assign(heap.top(), ""); return codes; }
struct HuffmanEncoded { std::string encoded; HuffmanCodes codes; };
inline HuffmanEncoded huffmanEncode(const std::string& text) { auto codes = huffmanCodes(text); std::string encoded; for (const auto& symbol : utf8Symbols(text)) encoded += codes.at(symbol); return {encoded, codes}; }
inline std::string huffmanDecode(const std::string& encoded, const HuffmanCodes& codes) { std::map<std::string, std::string> reverse; for (const auto& [symbol, code] : codes) reverse[code] = symbol; std::string result, buffer; for (char bit : encoded) { buffer += bit; auto it = reverse.find(buffer); if (it != reverse.end()) { result += it->second; buffer.clear(); } } return result; }
}
