namespace Algorithms.Mathematics;
public static class Matrices
{
    public static double[][] Identity(int size) => Enumerable.Range(0, size).Select(i => Enumerable.Range(0, size).Select(j => i == j ? 1d : 0d).ToArray()).ToArray();
    public static double[][] Multiply(double[][] a, double[][] b) { var inner = b.Length; var cols = inner == 0 ? 0 : b[0].Length; if ((a.Length == 0 ? 0 : a[0].Length) != inner) throw new ArgumentException("Columns of A must match rows of B"); var result = a.Select(_ => new double[cols]).ToArray(); for (var i = 0; i < a.Length; i++) for (var k = 0; k < inner; k++) { var aik = a[i][k]; if (aik == 0) continue; for (var j = 0; j < cols; j++) result[i][j] += aik * b[k][j]; } return result; }
    public static double[][] Transpose(double[][] matrix) => Enumerable.Range(0, matrix.Length == 0 ? 0 : matrix[0].Length).Select(j => matrix.Select(row => row[j]).ToArray()).ToArray();
    public static double[][] MatrixPower(double[][] matrix, int exponent) { var result = Identity(matrix.Length); var b = matrix.Select(r => r.ToArray()).ToArray(); while (exponent > 0) { if ((exponent & 1) != 0) result = Multiply(result, b); b = Multiply(b, b); exponent /= 2; } return result; }
    public static double Determinant(double[][] matrix) { var n = matrix.Length; var m = matrix.Select(r => r.ToArray()).ToArray(); var det = 1d; for (var col = 0; col < n; col++) { var pivot = col; for (var row = col + 1; row < n; row++) if (Math.Abs(m[row][col]) > Math.Abs(m[pivot][col])) pivot = row; if (Math.Abs(m[pivot][col]) < 1e-12) return 0; if (pivot != col) { (m[pivot], m[col]) = (m[col], m[pivot]); det = -det; } det *= m[col][col]; for (var row = col + 1; row < n; row++) { var f = m[row][col] / m[col][col]; for (var k = col; k < n; k++) m[row][k] -= f * m[col][k]; } } return det; }
    public static double[]? SolveLinearSystem(double[][] a, IReadOnlyList<double> b) { var n = a.Length; var m = a.Select((r, i) => r.Append(b[i]).ToArray()).ToArray(); for (var col = 0; col < n; col++) { var pivot = col; for (var row = col + 1; row < n; row++) if (Math.Abs(m[row][col]) > Math.Abs(m[pivot][col])) pivot = row; if (Math.Abs(m[pivot][col]) < 1e-12) return null; (m[pivot], m[col]) = (m[col], m[pivot]); for (var row = 0; row < n; row++) { if (row == col) continue; var f = m[row][col] / m[col][col]; for (var k = col; k <= n; k++) m[row][k] -= f * m[col][k]; } } return m.Select((r, i) => r[n] / r[i]).ToArray(); }
}
