#pragma once
#include "../../shared/json.hpp"
namespace algs {
struct WeatherService { virtual ~WeatherService() = default; virtual std::future<double> temperature(std::string city) = 0; };
class CachingWeatherProxy : public WeatherService { struct Entry { double value, expiresAt; }; WeatherService& service; double ttlMs; std::function<double()> now; std::map<std::string, Entry> cache; std::mutex mutex; public: CachingWeatherProxy(WeatherService& service, double ttlMs = 60000, std::function<double()> now = [] { return double(nowMs()); }): service(service), ttlMs(ttlMs), now(std::move(now)) {} std::future<double> temperature(std::string city) override { { std::lock_guard lock(mutex); auto it = cache.find(city); if (it != cache.end() && it->second.expiresAt > now()) return readyFuture(it->second.value); } return std::async(std::launch::async, [this, city = std::move(city)] { auto value = service.temperature(city).get(); std::lock_guard lock(mutex); cache[city] = {value, now() + ttlMs}; return value; }); } };
class AccessControlProxy : public WeatherService { WeatherService& service; std::function<bool()> isAllowed; public: AccessControlProxy(WeatherService& service, std::function<bool()> isAllowed): service(service), isAllowed(std::move(isAllowed)) {} std::future<double> temperature(std::string city) override { if (!isAllowed()) return failedFuture<double>(std::make_exception_ptr(std::runtime_error("Access denied"))); return service.temperature(std::move(city)); } };
class ValidatedObject { Json::Object& target; std::function<bool(const std::string&, const Json&)> validate; public: ValidatedObject(Json::Object& target, std::function<bool(const std::string&, const Json&)> validate): target(target), validate(std::move(validate)) {} const Json& get(const std::string& key) const { return target.at(key); } void set(std::string key, Json value) { if (!validate(key, value)) throw std::invalid_argument("Invalid value for " + key); target[std::move(key)] = std::move(value); } };
inline ValidatedObject createValidatedObject(Json::Object& target, std::function<bool(const std::string&, const Json&)> validate) { return ValidatedObject(target, std::move(validate)); }
}
