#pragma once
#include "../../support.hpp"
#include <cmath>
namespace algs {
struct Point { double x, y; bool operator==(const Point&) const = default; };
inline double cross(Point o, Point a, Point b) { return (a.x - o.x) * (b.y - o.y) - (a.y - o.y) * (b.x - o.x); }
inline double distance(Point a, Point b) { return std::hypot(a.x - b.x, a.y - b.y); }
inline std::vector<Point> convexHull(std::vector<Point> points) { std::stable_sort(points.begin(), points.end(), [](auto a, auto b) { return a.x == b.x ? a.y < b.y : a.x < b.x; }); if (points.size() < 3) return points; auto build = [](const std::vector<Point>& sequence) { std::vector<Point> hull; for (auto point : sequence) { while (hull.size() >= 2 && cross(hull[hull.size() - 2], hull.back(), point) <= 0) hull.pop_back(); hull.push_back(point); } hull.pop_back(); return hull; }; auto lower = build(points); std::reverse(points.begin(), points.end()); auto upper = build(points); lower.insert(lower.end(), upper.begin(), upper.end()); return lower; }
inline double polygonArea(const std::vector<Point>& polygon) { double area = 0; for (std::size_t i = 0; i < polygon.size(); ++i) { auto a = polygon[i], b = polygon[(i + 1) % polygon.size()]; area += a.x * b.y - b.x * a.y; } return std::abs(area) / 2; }
inline bool pointInPolygon(Point point, const std::vector<Point>& polygon) { bool inside = false; if (polygon.empty()) return false; for (std::size_t i = 0, j = polygon.size() - 1; i < polygon.size(); j = i++) { auto a = polygon[i], b = polygon[j]; if ((a.y > point.y) != (b.y > point.y) && point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x) inside = !inside; } return inside; }
inline bool segmentsIntersect(Point p1, Point p2, Point q1, Point q2) { auto sign = [](double v) { return (v > 0) - (v < 0); }; auto on = [](Point p, Point q, Point r) { return std::min(p.x, r.x) <= q.x && q.x <= std::max(p.x, r.x) && std::min(p.y, r.y) <= q.y && q.y <= std::max(p.y, r.y); }; int a = sign(cross(p1, p2, q1)), b = sign(cross(p1, p2, q2)), c = sign(cross(q1, q2, p1)), d = sign(cross(q1, q2, p2)); return (a != b && c != d) || (!a && on(p1, q1, p2)) || (!b && on(p1, q2, p2)) || (!c && on(q1, p1, q2)) || (!d && on(q1, p2, q2)); }
struct ClosestPairResult { Point a, b; double distance; };
inline std::optional<ClosestPairResult> closestPair(std::vector<Point> points) { if (points.size() < 2) return {}; std::stable_sort(points.begin(), points.end(), [](auto a, auto b) { return a.x < b.x; }); ClosestPairResult best{points[0], points[1], distance(points[0], points[1])}; auto update = [&](Point a, Point b) { auto d = distance(a, b); if (d < best.distance) best = {a, b, d}; }; std::function<std::vector<Point>(std::size_t, std::size_t)> solve = [&](auto left, auto right) { if (right - left <= 3) { for (auto i = left; i < right; ++i) for (auto j = i + 1; j < right; ++j) update(points[i], points[j]); std::vector<Point> part(points.begin() + left, points.begin() + right); std::stable_sort(part.begin(), part.end(), [](auto a, auto b) { return a.y < b.y; }); return part; } auto mid = (left + right) / 2; double x = points[mid].x; auto a = solve(left, mid), b = solve(mid, right); std::vector<Point> merged; std::merge(a.begin(), a.end(), b.begin(), b.end(), std::back_inserter(merged), [](auto p, auto q) { return p.y < q.y; }); std::vector<Point> strip; for (auto p : merged) if (std::abs(p.x - x) < best.distance) strip.push_back(p); for (std::size_t i = 0; i < strip.size(); ++i) for (auto j = i + 1; j < strip.size() && strip[j].y - strip[i].y < best.distance; ++j) update(strip[i], strip[j]); return merged; }; solve(0, points.size()); return best; }
}
