package shared;
import java.util.*;

public final class Json {
    private final String source;private int position;
    private Json(String source){this.source=source;}
    private void space(){while(position<source.length()&&Character.isWhitespace(source.charAt(position)))position++;}
    private char consume(){if(position>=source.length())throw new IllegalArgumentException("Unexpected end of JSON");return source.charAt(position++);}
    private String string(){if(consume()!='"')throw new IllegalArgumentException();StringBuilder b=new StringBuilder();while(true){char c=consume();if(c=='"')return b.toString();if(c=='\\'){char e=consume();switch(e){case '"','\\','/'->b.append(e);case 'b'->b.append('\b');case 'f'->b.append('\f');case 'n'->b.append('\n');case 'r'->b.append('\r');case 't'->b.append('\t');case 'u'->{b.append((char)Integer.parseInt(source.substring(position,position+4),16));position+=4;}default->throw new IllegalArgumentException();}}else b.append(c);}}
    private Object value(){space();char c=source.charAt(position);if(c=='"')return string();if(c=='['){consume();List<Object> a=new ArrayList<>();space();if(source.charAt(position)==']'){consume();return a;}while(true){a.add(value());space();c=consume();if(c==']')return a;if(c!=',')throw new IllegalArgumentException();}}if(c=='{'){consume();Map<String,Object> m=new LinkedHashMap<>();space();if(source.charAt(position)=='}'){consume();return m;}while(true){space();String key=string();space();if(consume()!=':')throw new IllegalArgumentException();m.put(key,value());space();c=consume();if(c=='}')return m;if(c!=',')throw new IllegalArgumentException();}}for(String literal:List.of("true","false","null"))if(source.startsWith(literal,position)){position+=literal.length();return literal.equals("null")?null:literal.equals("true");}int start=position;while(position<source.length()&&"0123456789+-.eE".indexOf(source.charAt(position))>=0)position++;if(start==position)throw new IllegalArgumentException("Invalid JSON");return Double.valueOf(source.substring(start,position));}
    public static Object parse(String source){var parser=new Json(source);Object value=parser.value();parser.space();if(parser.position!=source.length())throw new IllegalArgumentException("Trailing JSON");return value;}
    public static String stringify(Object value){if(value==null)return "null";if(value instanceof String s){StringBuilder b=new StringBuilder("\"");for(char c:s.toCharArray())switch(c){case '"'->b.append("\\\"");case '\\'->b.append("\\\\");case '\n'->b.append("\\n");case '\r'->b.append("\\r");case '\t'->b.append("\\t");default->{if(c<32)b.append(String.format("\\u%04x",(int)c));else b.append(c);}}return b.append('"').toString();}if(value instanceof Number||value instanceof Boolean)return value.toString();if(value instanceof Map<?,?> m){List<String> fields=new ArrayList<>();for(var e:m.entrySet())fields.add(stringify(e.getKey().toString())+":"+stringify(e.getValue()));return "{"+String.join(",",fields)+"}";}if(value instanceof Iterable<?> a){List<String> items=new ArrayList<>();for(Object v:a)items.add(stringify(v));return "["+String.join(",",items)+"]";}throw new IllegalArgumentException("Unsupported JSON value");}
}
